apiVersion: nais.io/v1alpha1
kind: Application

metadata:
  name: sykmelding-bucket-upload
  namespace: tsm
  labels:
    team: tsm
    system: mottak
spec:
  image: {{image}}
  port: 8080
  replicas:
    min: 1
    max: 10
    scalingStrategy:
      cpu:
        thresholdPercentage: 90
  resources:
    requests:
      cpu: 40m
      memory: 400Mi
  liveness:
    path: /internal/health
  readiness:
    path: /internal/health
  startup:
    failureThreshold: 10
    initialDelay: 20
    path: /internal/health
    periodSeconds: 5
    timeout: 1
  prometheus:
    enabled: true
    path: /internal/prometheus
  accessPolicy:
    outbound:
      rules:
        - application: logging
          namespace: nais-system
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: loki
  kafka:
    pool: nav-prod
  envFrom:
    - secret: sykmelding-bucket
