apiVersion: nais.io/v1alpha1
kind: Application

metadata:
  name: sykmelding-bucket-upload
  namespace: tsm
  labels:
    team: tsm
    system: mottak
spec:
  image: {{image}}
  port: 8080
  replicas:
    min: 1
    max: 10
  resources:
    requests:
      cpu: 50m
      memory: 256Mi
  liveness:
    path: /internal/health
  readiness:
    path: /internal/health
  startup:
    failureThreshold: 10
    initialDelay: 20
    path: /internal/health
    periodSeconds: 5
    timeout: 1
  prometheus:
    enabled: true
    path: /internal/prometheus
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: loki
        - id: elastic
  kafka:
    pool: nav-dev
  envFrom:
    - secret: sykmelding-bucket
    - secret: sykmelding-vedlegg-bucket

