[versions]
kotlin = "2.4.10"
logback = "1.5.38"
logbackEncoder = "9.0"
prometheus = "0.16.0"
googleStorage = "2.70.0"
kafka = "3.9.2"

[libraries]
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
prometheus-hotspot = { module = "io.prometheus:simpleclient_hotspot", version.ref = "prometheus" }
prometheus-client = { module = "io.prometheus:simpleclient_common", version.ref = "prometheus" }
logstash-logback-encoder = { module = "net.logstash.logback:logstash-logback-encoder", version.ref = "logbackEncoder" }
google-cloud-storage = { module = "com.google.cloud:google-cloud-storage", version.ref = "googleStorage" }
apache-kafka = { module = "org.apache.kafka:kafka-clients", version.ref = "kafka"}

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
